name: Deploy Reflekt App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload Laravel App via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Upload public/ contents into the root of reflect subdomain directory
      - name: Upload Laravel public folder
        uses: carlosbuitragosan/ftp-deploy-action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: ./
          state-name: reflect-public
          exclude: |
            .git*
            .github/
            README.md
            .editorconfig

      # Upload Laravel backend (excluding sensitive/dev files)
      - name: Upload Laravel backend files
        uses: carlosbuitragosan/ftp-deploy-action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          state-name: reflect-backend
          exclude: |
            .ftp-deploy-sync-state*
            .git/
            .github/
            .gitattributes
            .editorconfig
            .gitignore
            README.md
            node_modules/
            vendor/
            tests/
            .env
            .env.*
            public/
            package*.json
            vite.config.js
            tailwind.config.js
            postcss.config.js
            .prettierrc*
            .php-cs-fixer.*
          log-level: verbose
