name: Deploy Reflekt App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 1: Upload public/ folder
      - name: Upload Laravel public files
        uses: carlosbuitragosan/ftp-deploy-action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: public/
          state-name: reflect-public
          exclude: |
            .git*
            .github/
            .gitattributes
            .editorconfig
            README.md

      # Step 2: Upload Laravel backend files (excluding unwanted files/folders)
      - name: Upload Laravel backend files
        uses: carlosbuitragosan/ftp-deploy-action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          state-name: reflect-backend
          exclude: |
            .git/
            .git/*
            .gitignore
            .gitattributes
            .editorconfig
            README.md
            .github/
            .github/*
            node_modules/
            vendor/
            vendor/*
            .vendor/**
            tests/
            .env
            .env.example
            public/
            package*.json
            vite.config.js
            tailwind.config.js
            postcss.config.js
            .prettierrc*
            .php-cs-fixer.*
            README.md
          log-level: verbose
